urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from ragendja.urlsauto import urlpatterns
from ragendja.auth.urls import urlpatterns as auth_patterns
from django.contrib import admin

handler500 = 'ragendja.views.server_error'

urlpatterns = auth_patterns + patterns('',

    (r'^$', 'recipes.views.recipe_list'),
    (r'^recipe/add/$', 'recipes.views.add_recipe'),
    (r'^recipe/(?P<recipe_id>[^/]+)/$', 'recipes.views.recipe_detail'),
    (r'^recipe/(?P<recipe_id>[^/]+)/edit/$', 'recipes.views.edit_recipe'),
    (r'^api/recipes/$', 'recipes.handler.recipe_list'),
    (r'^image/$', 'recipes.views.image'),

) + urlpatterns

recipes/forms.py
from django import forms
from models import *

class RecipeForm(forms.Form):
    title       = forms.CharField()
    description = forms.CharField(widget = forms.widgets.Textarea())
    directions  = forms.CharField(widget = forms.widgets.Textarea())
    serves     = forms.CharField(help_text = 'eg: 4 people')

class IngredientForm(forms.Form):
    description = forms.CharField()

templates/add_recipe.html
{% extends 'base.html' %}

{% block title %}Cookiebook - {{ title }}{% endblock %}

{% block javascript_includes %}
<script type='text/javascript'>
    var add_new_ingredient_field = function() {
        var html = "" +
            "<div class='form-field-wrapper'>" +
            "    <input type='text' name='ingredient' placeholder='Enter an ingredient' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>" +
            "</div>";
        jQuery('div#ingredients-grouping').append(html);
    };

    jQuery(document).ready(function() {
        jQuery('span.ingredient-add-link').live('click', function() {
            add_new_ingredient_field();
        });

        jQuery('span.ingredient-delete-link').live('click', function() {
            jQuery(this).parent().remove();
        });
    });
</script>
{% endblock %}

{% block body %}
<div id='recipe-change-form'>
	<form action='{% url recipes.views.add_recipe %}' method='post' enctype='multipart/form-data'>
         {{ form.non_field_errors }}
         <div id='recipe-info'>
            <div class='form-field-wrapper'>
                {{ form.title.errors }}
                <label for='id_title'>Title:</label>
                {{ form.title }}
            </div>
            <div class='form-field-wrapper'>
                {{ form.picture.errors }}
                <label for='id_picture'>Picture:</label>
                <input type='file' name='picture' />
            </div>
            <div class='form-field-wrapper'>
                {{ form.description.errors }}
                <div><label for='id_description'>Description:</label></div>
                {{ form.description }}
            </div>
            <div class='form-field-wrapper'>
                {{ form.serves.errors }}
                <div><label for='id_serves'>Serves: </label>{{ form.serves }}</div>
            </div>
            <div class='form-field-wrapper'>
                {{ form.directions.errors }}
                <div><label for='id_directions'>Directions:</label></div>
                {{ form.directions }}
            </div>
        </div>
        <div id='ingredients-fields'>
            <label>Ingredients:</label><span class='ingredient-add-link'><img src='/media/images/icon_addlink.gif' /></span>
            <div id='ingredients-grouping'>
                <div class='form-field-wrapper'>
                    <input class='ingredient-field' type='text' name='ingredient' placeholder='Enter an ingredient' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>
                </div>
                <div class='form-field-wrapper'>
                    <input class='ingredient-field' type='text' name='ingredient' placeholder='Enter an ingredient' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>
                </div>
                <div class='form-field-wrapper'>
                    <input class='ingredient-field' type='text' name='ingredient' placeholder='Enter an ingredient' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>
                </div>
            </div>
        </div>
        <div style='clear: both;'></div>
        <div class='add-recipe-button'>
            <input type='submit' value='Add Recipe' />
        </div>
	</form>
    <div style='clear: both;'></div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html>
	<head>
		<title>{% block title %}Cookiebook{% endblock %}</title>
        <link rel='shortcut icon' href='/media/images/favicon.ico' type='image/x-icon' />
        <link type='text/css' rel='stylesheet' href='/media/css/main.css' />
		{% block css_includes %}
		{% endblock %}
        <script type='text/javascript' src='https://www.google.com/jsapi?key=ABQIAAAAbQsJ0L1UKKkRUfVHitoITRTZs1WKLUGL45zatV2xTRLqhxZxJhTtQIH72FHENBuIaoHW8zgvf0xPqQ'></script>
        <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js'></script>
		{% block javascript_includes %}
		{% endblock %}
		<meta name="viewport" content="width=320" />
		<meta name="viewport" content="user-scalable=false" />
	</head>
	<body>
        <div id='top-bar'>
        </div>

        <div id='header'>
            <a href='/'><img src='/media/images/logo.png' border='0' /></a>
        </div>
		{% block body %}
		{% endblock %}
    <div id='footer'>
        <img src="http://code.google.com/appengine/images/appengine-silver-120x30.gif" alt="Powered by Google App Engine" />
    </div>
	</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %}Cookiebook - {{ recipe.title }}{% endblock %}

{% block body %}
<div id='recipe-detail' class='subject-header'>
    <h1>{{ recipe.title }}</h1>
    <div id='recipe-detail-body' style='width: {% if recipe.picture %}480px{% else %}100%{% endif %};'>
        <div id='recipe-detail-description'>
            <div><label>Description:</label></div>
            {{ recipe.description }}
        </div>
        {% if recipe.serves %}
        <div id='recipe-detail-serves'>
            <div><label>Serves: </label>{{ recipe.serves }}</div>
        </div>
        {% endif %}
        <div id='recipe-detail-ingredients'>
            <div><label>Ingredients:</label></div>
            <ul>
            {% for ingredient in recipe.ingredient_set %}
                <li>{{ ingredient.description }}</li>
            {% endfor %}
            </ul>
        </div>
        <div id='recipe-detail-directions'>
            <div><label>Directions:</label></div>
            {{ recipe.directions }}
        </div>
    </div>
    <div id='recipe-image'>
        {% if recipe.picture %}
            <img src='/image/?img_id={{ recipe.key }}' />
        {% endif %}
    </div>
    <div style='clear: both;'></div>
    {% if show_edit_button %}
    <div class='add-recipe-button'>
        <input type='button' value='Edit this recipe' onClick='location.href = "/recipe/{{ recipe.key }}/edit/"' />
    </div>
    {% endif %}
</div>
{% endblock %}

templates/edit_recipe.html
{% extends 'base.html' %}

{% block title %}Edit {{ recipe.title }}{% endblock %}

{% block javascript_includes %}
<script type='text/javascript'>
    var add_new_ingredient_field = function() {
        var html = "" +
            "<div class='form-field-wrapper'>" +
            "    <input type='text' name='ingredient' placeholder='Enter an ingredient' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>" +
            "</div>";
        jQuery('div#ingredients-grouping').append(html);
    };

    jQuery(document).ready(function() {
        jQuery('span.ingredient-add-link').live('click', function() {
            add_new_ingredient_field();
        });

        jQuery('span.ingredient-delete-link').live('click', function() {
            jQuery(this).parent().remove();
        });
    });
</script>
{% endblock %}

{% block body %}
<div id='recipe-change-form'>
    <form action='{% url recipes.views.edit_recipe recipe.key %}' method='post' enctype='multipart/form-data'>
         <div id='recipe-info'>
            <div class='form-field-wrapper'>
                <label for='id_title'>Title:</label>
                <input type='text' name='title' id='id_title' value='{{ recipe.title }}' />
            </div>
            <div class='form-field-wrapper'>
                {% if recipe.picture %}
                <div id='edit-image'>
                    <img src='/image/?img_id={{ recipe.key }}' width='100' />
                </div>
                {% endif %}
                <label for='id_picture'>Picture:</label>
                <input type='file' name='picture' value='' />
            </div>
            <div class='form-field-wrapper'>
                <div><label for='id_description'>Description:</label></div>
                <textarea name="description" id="id_description">{{ recipe.description }}</textarea>
            </div>
            <div class='form-field-wrapper'>
                <div><label for='id_serves'>Serves: </label><input id='id_serves' name='serves' type='text' value='{{ recipe.serves }}' /></div>
            </div>
            <div class='form-field-wrapper'>
                <div><label for='id_directions'>Directions:</label></div>
                <textarea name="directions" id="id_directions">{{ recipe.directions }}</textarea>
            </div>
        </div>
        <div id='ingredients-fields'>
            <label>Ingredients:</label><span class='ingredient-add-link'><img src='/media/images/icon_addlink.gif' /></span>
            <div id='ingredients-grouping'>
                {% for ingredient in recipe.ingredient_set %}
                <div class='form-field-wrapper'>
                    <input class='ingredient-field' type='text' name='ingredient' value='{{ ingredient.description }}' /><span class='ingredient-delete-link'><img src='/media/images/icon_deletelink.gif' /></span>
                </div>
                {% endfor %}
            </div>
        </div>
        <div style='clear: both;'></div>
        <div class='add-recipe-button'>
            <input type='submit' value='Save Changes' />
        </div>
    </form>
    <div style='clear: both;'></div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Cookiebook{% endblock %}

{% block body %}
<div class='search-box'>
    <form action='{% url recipes.views.recipe_list %}' method='GET'>
        <input type='text' name='query' placeholder='Search' />
        <input type='submit' name='submit' value='Search' />
    </form>
</div>
<div id='add-recipe-top' class='add-recipe-button'>
    <input type='button' value='Add a recipe' onClick='location.href = "/recipe/add/"' />
</div>
<table id='recipe-list'>
    <tr class='subject-header'>
        <td>Title</td>
        <td>Description</td>
        <td>Added by</td>
        <td>Published</td>
    </tr>
{% for recipe in recipe_list %}
    <tr>
        <td>
            <a href='/recipe/{{ recipe.key|escape }}/'>{{ recipe.title|escape }}</a>
        </td>
        <td>
            {{ recipe.description|escape }}
        </td>
        <td>
            {{ recipe.added_by|escape }}
        </td>
        <td>
            {{ recipe.published|escape }}
        </td>
    </tr>
{% endfor %}
</table>
<div id='add-recipe-bottom' class='add-recipe-button'>
    <input type='button' value='Add a recipe' onClick='location.href = "/recipe/add/"' />
</div>

{% endblock %}